
test-attribute: NewValueFromSampleClientProperties

api.title=Documentacion Microservicio JPA - Actividad 6
api.description=Gestion de Grados y Alumnos con persistencia JPA
api.contact.name=Patricio Marcos Bibang Mba Sima
api.version=1.0.0
